version: '3'

services:
  otto:
    image: kopiro/otto
    restart: always
    volumes:
    - otto-cache:/app/cache
    - otto-storage:/app/storage
    - otto-tmp:/app/tmp
    - otto-log:/app/log
    - ./keys:/app/keys
    - ./config.json:/app/config.json 
    ports:
    - 8880:8880
    - 8881:8881
    - 8882:8882

volumes:
  otto-cache:
  otto-storage:
  otto-tmp:
  otto-log: