version: '3'

services:
  app:
    image: kopiro/otto
    restart: always
    volumes:
    - cache:/app/cache
    - storage:/app/storage
    - tmp:/app/tmp
    - log:/app/log
    - ./keys:/app/keys
    - ./config.json:/app/config.json 
    ports:
    - 8880:8880
    - 8881:8881
    - 8882:8882

  db:
    image: mongo
    restart: always
    volumes:
    - db:/data/db

volumes:
  cache:
  storage:
  tmp:
  log:
  db: